// <auto-generated />
namespace Pixel_Art_Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PostsAndCategoriesTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostsAndCategoriesTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201809290626120_PostsAndCategoriesTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
